# Copyright (c) Meta Platforms, Inc. and affiliates.

robust_depth_matching:
  name: robust_depth_matching
  config:
    inputs: [bg_depths,gt_depths,depth_mask,global_step]
    alpha: 0.1
    start_step: 200
