# Copyright (c) Meta Platforms, Inc. and affiliates.

name: omnimatte
config:
  n_frames:
  image_hw:
  homography_bounds:
  homography_size:
  network_normalization: batch
  max_frames: 200
  hidden_channels: 64
  coarseness: 10
  feature_mode: noise
  feature_config:
    channels: 13
train: true
optim:
  lr: 0.001
